### ISSUE TITLE
Consider moving JSON serialization boundry

### ISSUE THREAD

**Issue by SebastianEdwards** [guillec/json-patch#5]
I like the fact that we can patch Ruby hashes by building a `Patch` object and `#call`ing on it; perhaps it would also make sense if this returned another Ruby object for consistency. JSON serialization could take place in `JSON#patch`.

**Comment by guillec** [comment]
Makes sense I will implement.

**Comment by guillec** [comment]
Check it out! Thanks again for the comments.
