### ISSUE TITLE
Consider running against the offical tests

### ISSUE THREAD

**Issue by steveklabnik** [guillec/json-patch#7]
https://github.com/json-patch/json-patch-tests

@tenderlove tests hana with https://github.com/tenderlove/hana/blob/master/test/test_ietf.rb

**Comment by guillec** [comment]
Thanks, will do!

**Comment by guillec** [comment]
Boom! IETF tests.json file is now in place. Working on the spec_tests.json laters today.

**Comment by steveklabnik** [comment]
Wooooo!
